language: erlang
otp_release:
 - 19.2
 - 18.3
before_install:
 - sudo apt-key add ./test/ubuntu_extras_pub_key
 - sudo add-apt-repository -y ppa:cassou/emacs
 - sudo apt-get update -qq
 - sudo apt-get install -y -qq ${EMACS} erlang-debugger
 - |
   if [ "${EMACS}" == "emacs23" ]; then
     bash test/install-erlang-mode.sh
     bash test/install-ert.sh
     git submodule update --init
   fi
 - |
   if [ "${EMACS}" == "emacs24" ]; then
     emacs -Q --batch -L ${PWD} -l test/package-install-deps.el
   fi
env:
 - EMACS=emacs23
 - EMACS=emacs24
script:
 - "make -s test"
